### task 1

In [11]:
# Import numpy as np
import numpy as np
a = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])
b = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])
# use np.intersect1d function to get the value
print(np.intersect1d(a,b))

[2 4]


### task 2

In [5]:
# create array a range from 1 to 15
a = np.arange(1,16)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [7]:
# reshape the array first
a=a.reshape(3,5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [8]:
# reshape array again for a 5x3 form
a.T

array([[ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14],
       [ 5, 10, 15]])

### task 3

In [ ]:
# create two arrays a, b

In [34]:
a = np.array([12, 5, 7, 15, 3, 1, 8])
b = np.array([14, 6, 3, 11, 19, 12, 5])

In [37]:
# Write a Python/Numpy code block that removes from array a any items that are also present in array b.
# use np.itersect1d function, Value P
P = np.intersect1d(a, b)
for i in range(len(P)):
    a = a[a!=P[i]]  
print(a)

[ 7 15  1  8]


### task 4

1. From Google, the distance between nyc to key west is 1443 miles
2. 4 days, no cycling
3. use np.random.randint(30,1443,35), which means generate 35 random integer numbers, the range is 1 to 1443.
4. use np.sort function, so the result will be cumulative miles of the recorded each day during the trip
5. np.diff(a) funciton to get the total miles 
6. combine two arrays, to get the complete total miles

In [49]:
import numpy as np
record = np.random.randint(30,1443,35)
for i in np.random.randint(1,34,4):
    record[i]=record[i-1]
    
record[34] = 1443
daily = np.sort(record)
print(daily)

[  60   60  226  231  380  418  483  569  572  604  612  637  637  654
  747  749  751  753  809  871  885  919  934  960  960  981  990  990
 1012 1072 1091 1091 1260 1386 1443]


In [50]:
i = daily[0]
each_day = np.append(i,np.diff(daily))
print(each_day)

[ 60   0 166   5 149  38  65  86   3  32   8  25   0  17  93   2   2   2
  56  62  14  34  15  26   0  21   9   0  22  60  19   0 169 126  57]


### task 5

In [18]:
import pandas
import numpy as np

In [51]:
# supress scientific notation
np.set_printoptions(suppress = True)
# read the data file from Github and convert to a numpy
nyc_water = pandas.read_csv('https://raw.githubusercontent.com/jtopor/DAV-5400/master/Week4/Water_Consumption_In_The_New_York_City.csv').as_matrix()
type(nyc_water)

/Users/sunheepark/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:4: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  after removing the cwd from sys.path.


numpy.ndarray

In [52]:
print(nyc_water)

[[   1979.  7102100.     1512.      213. ]
 [   1980.  7071639.     1506.      213. ]
 [   1981.  7089241.     1309.      185. ]
 [   1982.  7109105.     1382.      194. ]
 [   1983.  7181224.     1424.      198. ]
 [   1984.  7234514.     1465.      203. ]
 [   1985.  7274054.     1326.      182. ]
 [   1986.  7319246.     1351.      185. ]
 [   1987.  7342476.     1447.      197. ]
 [   1988.  7353719.     1484.      202. ]
 [   1989.  7344175.     1402.      191. ]
 [   1990.  7335650.     1424.      194. ]
 [   1991.  7374501.     1469.      199. ]
 [   1992.  7428944.     1369.      184. ]
 [   1993.  7506166.     1368.5     182. ]
 [   1994.  7570458.     1357.7     179. ]
 [   1995.  7633040.     1325.7     174. ]
 [   1996.  7697812.     1297.9     169. ]
 [   1997.  7773443.     1205.5     155. ]
 [   1998.  7858259.     1219.5     155. ]
 [   1999.  7947660.     1237.2     156. ]
 [   2000.  8008278.     1240.4     155. ]
 [   2001.  8024963.5    1184.      148. ]
 [   2002. 

In [23]:
#use 'max' function to get the maxinum values
nyc_water[:,2].max()

1512.0

In [25]:
# create array 'calendar'
calendar=np.shape(nyc_water)
# how many calendar years are showed in this data set?
calendar[0]

39

In [27]:
# create the other array 
#3 What is the mean and the standard deviation of the per capita daily water consumption?
# use nyc_water[:,3] to slice this data set and get the per capita daily water consumption yearly
# use mean() function to get the mean values
print('consump:',nyc_water[:,3].mean())


consump: 160.30769230769232


In [53]:
# use np.std functin to get the standard value
print('standard:', np.std(nyc_water[:,3]))

standard: 31.51894330370624
